version: "3.9"
services:
  web:
    build: .
    depends_on:
      - postgres
    networks:
      - postgres_network
    environment:
      - PYTHONUNBUFFERED=0
    env_file:
      - .env


  postgres:
    container_name: postgres
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    env_file:
      - .env
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql
      - article-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres_network

volumes:
  article-data:

networks:
  postgres_network:
    driver: bridge